// Copies the ABIs the frontend needs into app/launchpad/_lib/abi.ts
const fs = require("fs");
const pick = (n) => JSON.parse(fs.readFileSync(`artifacts/src/${n}.sol/${n}.json`, "utf8")).abi;
const out = `// Generated by contracts/script/export-abi.js — do not edit by hand.
export const LaunchFactoryAbi = ${JSON.stringify(pick("LaunchFactory"))} as const;
export const FeeLockerAbi = ${JSON.stringify(pick("FeeLocker"))} as const;
export const FounderVaultAbi = ${JSON.stringify(pick("FounderVault"))} as const;
export const RewardsDistributorAbi = ${JSON.stringify(pick("RewardsDistributor"))} as const;
`;
fs.writeFileSync("../app/launchpad/_lib/abi.ts", out);
console.log("wrote app/launchpad/_lib/abi.ts");
