// Copies the ABIs the frontend needs into app/launchpad/_lib/abi.ts
const fs = require("fs");
const pick = (n) => JSON.parse(fs.readFileSync(`artifacts/src/${n}.sol/${n}.json`, "utf8")).abi;
const pickAt = (p, n) => JSON.parse(fs.readFileSync(`artifacts/src/${p}/${n}.json`, "utf8")).abi;
const out = `// Generated by contracts/script/export-abi.js — do not edit by hand.
export const LaunchFactoryAbi = ${JSON.stringify(pick("LaunchFactory"))} as const;
export const FeeLockerAbi = ${JSON.stringify(pick("FeeLocker"))} as const;
export const FounderVaultAbi = ${JSON.stringify(pick("FounderVault"))} as const;
export const RewardsDistributorAbi = ${JSON.stringify(pick("RewardsDistributor"))} as const;
export const LaunchFactoryV4Abi = ${JSON.stringify(pickAt("v4/LaunchFactoryV4.sol", "LaunchFactoryV4"))} as const;
export const V4FeeLockerAbi = ${JSON.stringify(pickAt("v4/V4FeeLocker.sol", "V4FeeLocker"))} as const;
export const LaunchHookAbi = ${JSON.stringify(pickAt("v4/LaunchHook.sol", "LaunchHook"))} as const;
export const StateViewAbi = ${JSON.stringify(pickAt("v4/IUniswapV4.sol", "IStateView"))} as const;
`;
fs.writeFileSync("../app/launchpad/_lib/abi.ts", out);
console.log("wrote app/launchpad/_lib/abi.ts");
